import type { TransliterationTable } from "./types"

/** Symbols spelled out in English (`&`, `©`, currency signs) or turned into separators (dashes, quotes, bullets). */
export const symbols: TransliterationTable = {
  "&": " and ",
  "©": " c ",
  "®": " r ",
  "™": " tm ",
  "℠": " sm ",
  "♥": " love ",
  "❤": " love ",
  "🦄": " unicorn ",
  "€": " euro ",
  "£": " pound ",
  "¥": " yen ",
  "¢": " cent ",
  "₺": " lira ",
  "₹": " rupee ",
  "₽": " ruble ",
  "₩": " won ",
  "₪": " shekel ",
  "₫": " dong ",
  "₴": " hryvnia ",
  "₦": " naira ",
  "฿": " baht ",
  "₿": " bitcoin ",
  "₱": " peso ",
  "₸": " tenge ",
  "₾": " lari ",
  "₮": " tugrik ",
  "₼": " manat ",
  "₡": " colon ",
  "₲": " guarani ",
  "₭": " kip ",
  "₨": " rupee ",
  "‰": " permille ",
  "°": " deg ",
  "№": " no ",
  µ: " u ",
  "×": " x ",
  "∞": " infinity ",
  "∑": " sum ",
  "√": " sqrt ",
  π: " pi ",
  "§": " section ",
  "¶": " paragraph ",
  "†": " ",
  "‡": " ",
  "•": " ",
  "…": " ",
  "–": " ",
  "—": " ",
  "«": " ",
  "»": " ",
  "“": " ",
  "”": " ",
  "„": " ",
  "‘": "",
  "’": "",
  "‚": "",
  "‛": "",
  "‹": " ",
  "›": " ",
  "¿": " ",
  "¡": " ",
  "′": " ",
  "″": " ",
}
